apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
spec:
  containers:
  - name: my-container2
    image: nginx:1.14.2
    volumeMounts:
    - name: config-volume
      mountPath: /opt
  volumes:
  - name: config-volume
    configMap:
      name: my-config
